// Generated by CoffeeScript 1.6.2
(function() {
  window.Game = {
    start: function() {
      this.STAGE_WIDTH = 800;
      this.STAGE_HEIGHT = 600;
      Crafty.init(this.STAGE_WIDTH, this.STAGE_HEIGHT);
      Crafty.sprite(100, 100, 'assets/img/building1.gif', {
        building1: [0, 0]
      });
      Crafty.sprite(200, 150, 'assets/img/building2.gif', {
        building2: [0, 0]
      });
      Crafty.sprite(60, 60, 'assets/img/potato.gif', {
        potato: [0, 0]
      });
      Crafty.sprite(40, 40, 'assets/img/pigeons.gif', {
        pigeon: [0, 0]
      });
      Crafty.sprite(100, 60, 'assets/img/rat2.gif', {
        rat: [0, 0]
      });
      Crafty.sprite(70, 125, 'assets/img/gnome.gif', {
        gnome: [0, 0]
      });
      Crafty.sprite(98, 95, 'assets/img/gnomedeath.gif', {
        deadgnome: [0, 0]
      });
      Crafty.sprite(800, 600, 'assets/img/metrognome.gif', {
        loadimage: [0, 0]
      });
      return Crafty.scene("load");
    }
  };

}).call(this);
