// Generated by CoffeeScript 1.6.2
(function() {
  var ASSETS, DRUM_ASSETS;

  DRUM_ASSETS = ["assets/audio/ludum_beat.mp3", "assets/audio/ludum_beat.ogg", "assets/audio/ludum_beat.wav"];

  ASSETS = ['assets/img/building1.gif', 'assets/img/building2.gif', 'assets/img/potato.gif', 'assets/img/pigeons.gif', 'assets/img/rat2.gif', 'assets/img/gnome.gif', 'assets/img/gnomedeath.gif', 'assets/img/metrognome.gif'].concat(DRUM_ASSETS);

  Crafty.scene("load", function() {
    console.log("loading start");
    Crafty.audio.add("drum", DRUM_ASSETS);
    window.levelLoader = Crafty.e("LevelLoader");
    Crafty.load(ASSETS, function() {
      console.log("loading done");
      Crafty.scene("title");
    });
  });

  Crafty.scene("title", function() {
    var displayTitle, proceedToMain;

    proceedToMain = function() {
      console.log("Proceeding");
      return Crafty.scene("main");
    };
    displayTitle = function() {
      var proceedTimeout;

      console.log("displayTitle");
      this.logo = Crafty.e("2D, DOM, Sprite, Keyboard, loadimage");
      proceedTimeout = setTimeout(proceedToMain, 10000);
      return this.logo.bind('KeyDown', function() {
        console.log("KeyDown");
        clearTimeout(proceedTimeout);
        return proceedToMain();
      });
    };
    return displayTitle();
  });

  Crafty.scene("main", function() {
    console.log("main");
    this.freezer = Crafty.e('Freezable');
    this.freezer.freezableState = this.freezer.FreezableStates.active;
    Crafty('LevelLoader').reloadLevel();
  });

}).call(this);
